# fly.toml app configuration file generated for aged-cloud-8056 on 2023-09-19T11:33:57-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "aged-cloud-8056"
primary_region = "gru"

[env]
  PORT = "8080"
  
[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
